# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T01:14:54+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, UnsuportedSecurityStub
from fastapi import Query

from models import (
    Alt,
    FieldXgafv,
    GoogleCloudPrivatecatalogV1beta1SearchCatalogsResponse,
    GoogleCloudPrivatecatalogV1beta1SearchProductsResponse,
    GoogleCloudPrivatecatalogV1beta1SearchVersionsResponse,
)

app = MCPProxy(
    contact={'name': 'Google', 'url': 'https://google.com'},
    description='Enable cloud users to discover enterprise catalogs and products in their organizations.',
    license={
        'name': 'Creative Commons Attribution 3.0',
        'url': 'http://creativecommons.org/licenses/by/3.0/',
    },
    termsOfService='https://developers.google.com/terms/',
    title='Cloud Private Catalog',
    version='v1beta1',
    servers=[{'url': 'https://cloudprivatecatalog.googleapis.com/'}],
)


@app.get(
    '/v1beta1/{resource}/catalogs:search',
    description=""" Search Catalog resources that consumers have access to, within the
scope of the consumer cloud resource hierarchy context. """,
    tags=['catalog_search_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def cloudprivatecatalog_organizations_catalogs_search(
    resource: str,
    page_size: Optional[int] = Query(None, alias='pageSize'),
    page_token: Optional[str] = Query(None, alias='pageToken'),
    query: Optional[str] = None,
    field__xgafv: Optional[FieldXgafv] = Query(None, alias='$.xgafv'),
    oauth_token: Optional[str] = None,
    callback: Optional[str] = None,
    alt: Optional[Alt] = 'json',
    key: Optional[str] = None,
    access_token: Optional[str] = None,
    upload_protocol: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    fields: Optional[str] = None,
    upload_type: Optional[str] = Query(None, alias='uploadType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1beta1/{resource}/products:search',
    description=""" Search Product resources that consumers have access to, within the
scope of the consumer cloud resource hierarchy context. """,
    tags=['catalog_search_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def cloudprivatecatalog_organizations_products_search(
    resource: str,
    page_size: Optional[int] = Query(None, alias='pageSize'),
    page_token: Optional[str] = Query(None, alias='pageToken'),
    query: Optional[str] = None,
    field__xgafv: Optional[FieldXgafv] = Query(None, alias='$.xgafv'),
    oauth_token: Optional[str] = None,
    callback: Optional[str] = None,
    alt: Optional[Alt] = 'json',
    key: Optional[str] = None,
    access_token: Optional[str] = None,
    upload_protocol: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    fields: Optional[str] = None,
    upload_type: Optional[str] = Query(None, alias='uploadType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1beta1/{resource}/versions:search',
    description=""" Search Version resources that consumers have access to, within the
scope of the consumer cloud resource hierarchy context. """,
    tags=['catalog_search_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def cloudprivatecatalog_organizations_versions_search(
    resource: str,
    page_size: Optional[int] = Query(None, alias='pageSize'),
    page_token: Optional[str] = Query(None, alias='pageToken'),
    query: Optional[str] = None,
    field__xgafv: Optional[FieldXgafv] = Query(None, alias='$.xgafv'),
    oauth_token: Optional[str] = None,
    callback: Optional[str] = None,
    alt: Optional[Alt] = 'json',
    key: Optional[str] = None,
    access_token: Optional[str] = None,
    upload_protocol: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    fields: Optional[str] = None,
    upload_type: Optional[str] = Query(None, alias='uploadType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
